### ISSUE TITLE
Data loss observed during coap NON and CON message communication.

### ISSUE THREAD

**Issue by dasdipanjan** [eclipse-californium/californium#2281] opened 2024-09-23 09:27 UTC
Hi Team,

We are using latest (version: '3.12.1') Californium COAP library  for our project. We are in Java based microservice architecture and one  of our microservice is producing data and another services are consuming this data. As per our requirement data producer service must have to publish data in at least   250 milli seconds. Our data is in JSON format. JSON messages are small in nature and similar for high rate data and few messages are in KB which can be published when there is change in system. As part of our POC we have developed one microservice which can publish data in every 250 milli seconds and 200 milli seconds. And developed sample client which can listen data. We have used CON message type for communication.  We are running our POC code in small hardware based Linux device (2GB RAM and Dual Core Processor). 

We observed that there is data loss. Some of the packet client was  not receiving. To solve the problem we have used custom configuration file. Changed few configuration. I have attached custom configuration file. Please check the same and also giving sample code which we are using during publish and receive.

In our actual data producer service we have 30 data published endpoints and 28 request /response endpoints API. We observe data loss between published and subscriber when system is in operation and also observe data loss when data publishing is happening in every 250ms and same time request response API also called.

//Data Publisher Code.

```
public class WeatherInfoPublisher extends CoapResource {
    private static final Logger logger = LoggerFactory.getLogger(WeatherInfoPublisher.class);
    private AtomicReference<String> mDataToBePublished;

    public WeatherInfoPublisher(String name, boolean visible) {
        super(name, visible);
        setObservable(true); // enable observing
        setObserveType(CoAP.Type.CON);
        super.setVisible(visible);
        super.getAttributes().addContentType(APPLICATION_JSON);
        mDataToBePublished = new AtomicReference<>();
    }

    @Override
    public void handleGET(CoapExchange exchange) {
        if (super.isObservable()) {
            exchange.respond(mDataToBePublished.get());
            logger.info("Weather information has been published.");
        }
    }

    public void publishData(String message) {
        if (mDataToBePublished != null) {
            mDataToBePublished.set(message);
            changed();
        }
    }
}
```

//Data Listening/Subscribe code.

```
public void startListenToWeatherData() {
        try {
            mMessageQueue = new ArrayBlockingQueue<>(10000);
            mObjectMapper = new ObjectMapper();
            mDataIndex = new AtomicLong(1);
            mReceivedDataCount = new AtomicInteger(1);
            CoapConfig.register();
            UdpConfig.register();
            mWeatherInfoClient = new CoapClient.Builder("127.0.0.1", 8080)
                    .scheme("coap").path("weatherinfo").query(new String[0]).create();
            logger.info("Coap URL for Weather Info : {}", mWeatherInfoClient.getURI());
            mWeatherInfoClient.useCONs();
            mWeatherInfoClient.observe(new CoapHandler() {
                @Override
                public void onLoad(CoapResponse coapResponse) {
                    try {
                        String weatherInformation = coapResponse.getResponseText();
                        mMessageQueue.put(weatherInformation);
                    } catch (InterruptedException e) {
                        logger.error(e.getMessage(), e);
                        Thread.currentThread().interrupt();
                    }
                }

                @Override
                public void onError() {
                    logger.info("Error occurred when client was listening weather information ");
                }
            });
            this.startDataAnalysis();
        } catch (Exception e) {
            logger.error("Error occurred when client was establishing connection for weather information ", e);
        }
    }
```

We have changed below mentioned properties in Configuration file.

COAP.MAX_MESSAGE_SIZE=10240
COAP.MAX_RESOURCE_BODY_SIZE=2097152
UDP.DATAGRAM_SIZE=2048
UDP.RECEIVER_THREAD_COUNT=5
UDP.RECEIVE_BUFFER_SIZE=
UDP.SENDER_THREAD_COUNT=5
UDP.SEND_BUFFER_SIZE=

[Configuration.zip](https://github.com/user-attachments/files/17095189/Configuration.zip)

I have attached Custom configuration file in ZIP format. Please check it.
Please suggest me how can I achieve no data loss. We observed when system is slightly loaded data loss are more observed.

**Comment by dasdipanjan** [comment] 2024-09-23 10:32
For experiment purpose we used COAP.MAX_RESOURCE_BODY_SIZE=2097152 which is maximum 2MB but in our actual service we kept this value as default. COAP.MAX_RESOURCE_BODY_SIZE=8192 and we observed when we keep COAP.MAX_MESSAGE_SIZE value as 1024, observer receives fragmented message. So that we changed to 10240. 

In our actual data producer service we have 30 observer/notify endpoints and 28 REST endpoints API. 
Among 30 observer/notify APIs only 2 APIs are notifying latest data in 250ms with size maximum 1KB and other 28 observer/notify endpoints are event based which runs parallelly but publish data when it is required. Event based API's can publish  maximum 2KB individually. 28 observer/notify endpoints  never notify latest data together. They are individual and notify data when there is change in data model. They do not notify data periodically. We are using this library last 3 years and when system is fully integrated we observed few data loss during random testing only. 

But in our actual application when we increased below mentioned two properties we are not observing data loss.
UDP.SEND_BUFFER_SIZE=102400
UDP.RECEIVE_BUFFER_SIZE=102400
We are using 3.8.0 in our actual service and before updating to 3.12.1 we were observing data loss. So we did POC with 3.12.1 and reporting our observation here.

**Comment by boaks** [comment] 2024-09-23 10:46
> COAP.MAX_RESOURCE_BODY_SIZE=8192 and we observed when we keep COAP.MAX_MESSAGE_SIZE value as 1024, observer receives fragmented message.

There is a slightly difference between fragmented UDP messages (out of the scope of Californium, depends a lot on your network) and a coap blockwise transfer (in the scope of Californium RFC7959).

> COAP.MAX_RESOURCE_BODY_SIZE=8192
> COAP.MAX_MESSAGE_SIZE=1024
 
If that causes something as "fragmentation" (I assume a blockwise transfer), then you send more than 1k. How large is your payload?

> From documentation we did not found solid information about custom configuration. Could you please help me to get documentation for custom configuration.

Unfortunately, there is no better documentation. In the very most cases, adapting the configuration requires a deeper knowledge of the network and coap (including the extensions as blockwise and observer/notify). Without that knowledge your in danger of wasting your time with an PoC, which just doesn't comply with the used RFCs.

**Comment by dasdipanjan** [comment] 2024-09-23 10:59
All of our microservices are running locally inside the device. They are communicating through local host. Maximum payload can be 5KB for some of our endpoints. With this COAP.MAX_MESSAGE_SIZE=10240 configuration we solved the fragmentation issue.

**Comment by boaks** [comment] 2024-09-23 11:09
> With this COAP.MAX_MESSAGE_SIZE=10240 configuration we solved the fragmentation issue.

No, that causes UDP fragmentation once you don't run that on "local host".
It only prevents using a coap blockwise transfer. 

> Could you please help us to decide highest frequency data transfer rate with no single packet loss?

With 5 KB message size? Chose an other protocol.

**Comment by dasdipanjan** [comment] 2024-09-23 11:27
Any Suggestion for other protocol and could you please tell me maximum how much payload can we notify using Californium's observer/notify API relation?

**Comment by boaks** [comment] 2024-09-23 11:53
Just use HTTP or MQTT. I don't know, if that works well, but a flood of 5k isn't the strength of CoAP.

CoAP is designed to send small messages and to work, if that happens also low frequently.
The "best message size" depends mainly on the MTU of your network. That may vary, if you use localhost, ethernet, wlan or cellular. Therefore it's pretty common to not use more than the 1024 bytes payload per message. If more is required to be transferred, then it's common to use a blockwise transfer according RFC7959, which split the large payload into several coap-messages.
Considering, that a server may server a couple of thousand clients, it's not considered, that each client sends too much messages. With the common max exchange time (247s) and a 16 bit Message ID that results in 65536/247 so about 265 messages per peer per second. If a blockwise uses 5 coap messages, then that results in about 53 "large application messages". 
It may be possible to increase that by a smaller max exchange time, but if that works, depends again on your network and application.
Beside of that limit caused by the MID size and max exchange time, a network with limited bandwidth will also either throttle or loss messages, if the amount of data is above the bandwidth. That's the reason, why the observer/notify you use doesn't grant to send all messages but rather to send the "latest changed value". 
Therefore,if you want to send "reliable" data from one peer to the other, just use POST requests. It's then up to your application to decide, if on network issues, the data sent is the old/delayed one, or the freshest and older data is dropped.

**Comment by dasdipanjan** [comment] 2024-09-23 12:16
Last question: Could you please tell me is there any way to check of ACK message for CON message in CoapResource implementation? Is there any call back API which I can override in implementation class of CoapResource  and check for ACK.

**Comment by boaks** [comment] 2024-09-23 12:55
The `CoapResource` represents the resource itself, there is no relation to ACKs there.
Coap messages are represented by `Message`, `Request`, `Response` and `EmptyMessage`. The `Message` supports to add `MessageObserver` (or `MessageObserverAdapter`) and there you may use/override the `onAcknowledgement()`. 

If one peer send a `Request` to the other, the `ACK` isn't the important point, it's the `Response`.
Only if you go for the observer/notify, the a notify is a `Response` and that my be a CON message. Then the ACK is pretty important.

**Comment by dasdipanjan** [comment] 2024-09-24 09:23
Thank you Sir for your valuable help. You can close this issue.

**Closed** 2024-09-24 09:42 UTC
