### ISSUE TITLE
Californium Deployment issues

### ISSUE THREAD

**Issue by DHBAT** [eclipse-californium/californium#2203] opened 2023-12-29 11:42 UTC
Download the ZIP file in the code and put it on the E drive for decompression. The computer environment is JDK 1.8, the Maven version is 3.6.1, and the system is Windows. Open the terminal in the root directory and execute the mvn install clean command. An error occurs during execution. The error message is as shown in the picture. How to solve this?

**Comment by DHBAT** [comment] 2023-12-29 11:45
They are error message
![_`NJFP@04 MA 4$AGPKO2SV](https://github.com/eclipse-californium/californium/assets/115906484/a16c6f25-f5b1-451e-9519-8dcac780dd30)

**Comment by boaks** [comment] 2023-12-29 14:35
Using Windows 11, maven 3.8.2, openjdk 17.0.9 I'm able to build it successfully.
The failure reported above for some unit tests (pictures are sooo bad ... text logs are much more helpful) is not reported on my systems. And the jvm doesn't crash on my systems. So overall, I'm not able to reproduce the above error. Maybe switching back to old maven and jdk versions will reproduce it, but then the fix will be to update them. 
So, what are the reasons to use jdk 1.8 for building?
For the release we use a maven toolchain, which enables to run maven with the jdk-17 but use java-7 to compile the build. Maybe you are also able to update maven, install jdk-17 additional and the define a toolchain for maven (see [build jdk7 compliant](https://github.com/eclipse-californium/californium#build-jdk7-compliant)).

**Comment by boaks** [comment] 2023-12-29 15:27
Also using the latest jdk-1.8 "works on my machine"

```
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\tools\apache-maven-3.8.2
Java version: 1.8.0_392, vendor: Temurin, runtime: C:\tools\jdk8u392-b08\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

Please try to use also a recent jdk1.8 build and at least maven 3.8.2.

**Comment by boaks** [comment] 2024-01-11 15:33
I have no idea what's going on on your side. I'm not an revapi expert. Could you please try

```
mvn clean install -Drevapi.skip=true
```

**Comment by DHBAT** [comment] 2024-01-11 15:36
Okay, I'm gonna try it now.
| |
dh14779715518
|
|
***@***.***
|
---- Replied Message ----
| From | Achim ***@***.***> |
| Date | 1/11/2024 23:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [eclipse-californium/californium] Californium Deployment issues (Issue #2203) |

I have no idea what's going on on your side. I'm not an revapi expert. Could you please try

mvn clean install -Drevapi.skip=true

**Comment by boaks** [comment] 2024-01-11 16:46
The only environment I know, where such errors occurs, are too less CPU power.
The may be caused either by a slow machine or by a container, which gets too low CPU assigned. Also RAM must be considered, otherwise that will also slow down a lot.

On what machine do you run the build? Do you use a container?

You may also try to skip the tests with 

```
mvn clean install -Drevapi.skip=true -DskipTests
```

**Comment by DHBAT** [comment] 2024-01-11 16:55
I'm running this on my laptop, not using a container. ok, next, I'll try to skip this tests



| |
dh14779715518
|
|
***@***.***
|
---- Replied Message ----
| From | Achim ***@***.***> |
| Date | 1/12/2024 00:47 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [eclipse-californium/californium] Californium Deployment issues (Issue #2203) |

The only environment I know, where such errors occurs, are too less CPU power.
The may be caused either by a slow machine or by a container, which gets too low CPU assigned. Also RAM must be considered, otherwise that will also slow down a lot.

On what machine do you run the build? Do you use a container?

You may also try to skip the tests with

mvn clean install -Drevapi.skip=true -DskipTests

**Comment by boaks** [comment] 2024-01-20 07:50
Does it work now? If so, please close this issue.

**Closed** 2024-02-10 07:17 UTC
Labels: waiting for feedback, could this be closed?
