### ISSUE TITLE
Dealing with RESPONSE_MATCHING parameter on device (reverse engineering)

### ISSUE THREAD

**Issue by developez** [eclipse-californium/californium#2156] opened 2023-07-12 07:59 UTC
Scenario:

1 device that connects under LWM2M protocol
1 back running leshan library (we have got the code)
1 back running with unknow software and unknow code

Behaviour: 

We running leshan server with this parameter:

    	networkConfig.setString(NetworkConfig.Keys.RESPONSE_MATCHING,"STRICT");

When the device does the registration process then we observe the /19/0/0 endpoint. When we touch the device, this sends a message to the server that is observed by the /19/0/0 observation, is this action we send a command to the device with this code:

```
this.server.getObservationService().addListener(this.observationListener);

private final ObservationListener observationListener = new ObservationListener() {

        @Override
        public void onResponse(Observation observation, Registration registration, ObserveResponse response) {      	

            var open_command= ...;       	

            WriteResponse write_response = this.ref_server.send(registration, new WriteRequest(19,1,0, open_command));
            if(write_response != null)
            {
                 ....

       }
```

All this works OK, but at 2-3 minutes when device is not touched, if you touch the device again, the device make the registration process again and the observation to the /19/0/0 needs to be done again to send commands because the previous observation is obsolete.

The log says this when the device connects again with the server after 2-3 minutes without interaction:

```
DEBUG BaseMatcher - re-created exchange from original observe request: CON-GET    MID= 6508, Token=41EFA768DDCD1227, OptionSet={"Observe":0, "Uri-Path":["19","0","0"]}, no payload
DEBUG UdpMatcher$4 - ignoring potentially forged response for token KeyToken[41EFA768DDCD1227] with non-matching endpoint context
```

(and then, the device does the de-registration and registration process again, and the, we need to reobservate the /19/0/0.

In other hand, if we use the parameter RELAXED:

    	networkConfig.setString(NetworkConfig.Keys.RESPONSE_MATCHING,"RELAXED");

The re-registration process is not done, but the sent command (ref_server.send) never achieves the device (the port of the device changed).

We dont know if the device uses DTLS, we think that we need to put the corrects parameters at the time to launch the leshan server. We have got another backend with unknow code that works without this re-registration or re-observation issues.

**Comment by sbernard31** [comment] 2023-07-12 10:01
I think this is a duplicate of : https://github.com/eclipse-leshan/leshan/issues/1471

And probably more a Leshan question than a Californium one.

So maybe this one should be closed.

**Comment by boaks** [comment] 2023-07-12 13:32
> we have got the code

Both, Leshan and Californium are Eclipse Open Source projects and so you should be able to get the code of both easily ;-).  

The leshan ticket already addressed the leshan specific part. Does this answer your question?

If not, are you common with IP-endpoints, IP-NATing, UDP and CoAP?

You may read [UDP / NATing](https://cloudcoap.net/blog/comparison/#DTLS), maybe that helps. If not, try to [wireshark](https://github.com/eclipse-californium/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing) your traffic on your server node, and analyze the packets on your own. I guess, you will see the changing ip-address/ports.

For `RESPONSE_MATCHING` (I guess, your code is using the older Californium 2) you may read 
[MatcherMode](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L62-L86)

If sending a request from the backend server to the device client doesn't work, check also the used ip-addresses. If leshan doesn't update that device ip-address to the fresh, then the message is sent to the "gone" address.
There have been a lot of discussion in LwM2M around that, I'm not sure, what the final conclusion was. But I guess the leshan project knows it. And once you pass the fresh device address to the coap request, californium will be able to reach the device.

**Closed** 2023-07-25 18:49 UTC
Labels: could this be closed?
