### ISSUE TITLE
App crashing with coap californium

### ISSUE THREAD

**Issue by SuneelUgar** [eclipse-californium/californium#2079] opened 2022-10-12 13:28 UTC
# App crashing with coap californium.

Java Application is using coap communication to publish data at every 50 ms.
Some times it crashes while publishing the data . 
Application has following two coap communcation:
1) publishing data @every 50ms.
2) Sending put request to another caop server @ every 10 seconds.

Version : 'californium-core', version: ['2.6.3']
Processor	: ARMv7 Processor rev 10 (v7l)
Hardware	: Freescale i.MX6 Quad/DualLite (Device Tree)
Java : 1.8
OS : Linux

Crash Dump:

[hs_err_pid1040.log](https://github.com/eclipse-californium/californium/files/9765189/hs_err_pid1040.log)

**Comment by boaks** [comment] 2022-10-14 08:42
Just as remark:
I was running Californium on an Raspberry PI for 2-3 years. Longterm-tests, loadtests. I never got a crashing vm.

Can we close this issue?

**Comment by SuneelUgar** [comment] 2022-10-14 08:46
We repeatedly seeing this issue and It is pointing to below code. Please check the stack trace below.

Stack: [0x60460000,0x604b0000],  sp=0x604ae9b0,  free space=314k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
v  ~BufferBlob::vtable chunks
j  org.eclipse.californium.elements.KeySetEndpointContextMatcher.isResponseRelatedToRequest(Lorg/eclipse/californium/elements/EndpointContext;Lorg/eclipse/californium/elements/EndpointContext;)Z+24
j  org.eclipse.californium.elements.UdpEndpointContextMatcher.isResponseRelatedToRequest(Lorg/eclipse/californium/elements/EndpointContext;Lorg/eclipse/californium/elements/EndpointContext;)Z+102
j  org.eclipse.californium.core.network.UdpMatcher$5.run()V+141
j  org.eclipse.californium.elements.util.SerialExecutor$1.run()V+35
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x1c928f]

**Comment by boaks** [comment] 2022-10-14 08:57
Again, AFAIK, a java-app is not considered to crash a jvm.

Running Californium for several years on PCs, cloud-vms and raspberry PIs I never had any jvm crash.

Do you use custom native functions, maybe your's or thirdparty?

Could you try to reproduce the issue using an raspberry PI (that's more or less the only ARM baed board I have)?
Could you try to isolate the issue in an sample, so I can retest on my side using an raspberry PI?

Without that, sorry, I don't know how to help.

**Comment by SuneelUgar** [comment] 2022-10-17 08:47
> Again, AFAIK, a java-app is not considered to crash a jvm.
> 
> Running Californium for several years on PCs, cloud-vms and raspberry PIs I never had any jvm crash.
> 
> Do you use custom native functions, maybe your's or thirdparty?
> 
> Could you try to reproduce the issue using an raspberry PI (that's more or less the only ARM based board I have)? Could you try to isolate the issue in an sample, so I can retest on my side using an raspberry PI?
> 
> Without that, sorry, I don't know how to help.

**Comment by SuneelUgar** [comment] 2022-10-17 08:51
Yes We use some native functions call but stack trace is pointing to californium code .
And this is happening when we have continuous data publish from coap server and  in between we send frequently put request to one more coap server. I will try to check whether i can reproduce it in sample application then share it with you.

**Comment by boaks** [comment] 2022-10-17 09:00
> Yes We use some native functions call but stack trace is pointing to californium code .

A mangling C pointer may cause that without issues in the java application.
There is nothing used in the java code, which kills a jvm. Beside of "memory-overflows", I therefore see no possible cause there. 

Remove your native stuff, maybe split it in a second jvm and use simple TCP betweenthe jvm  to exchange the data. I guess, the jvm without your functions will run stable, but the one with the native stuff will crash, then on other java calls.

**Comment by boaks** [comment] 2022-10-26 06:31
Any progress split off the custom native stuff into a different jvm?

**Comment by boaks** [comment] 2022-11-04 07:24
@SuneelUgar 

I assume, you found the bug inside your own native stuff. At least, you not able to reproduce this issue without your native code. If I'm wrong, just let us know.

**Comment by SuneelUgar** [comment] 2022-11-04 07:50
@boaks We do not have any issue in our native stuff. Even i tried using different native stuff same issue we observed.
I also tried using different coap library there we did not find this issue. I am trying to reproduce this issue in sample application with coap californium. Give me some time.

**Comment by boaks** [comment] 2022-11-04 07:57
> Even i tried using different native stuff same issue we observed.

Sorry, could please be precise: do you use custom native stuff? 
I already requested to split custom native stuff in different jvm.

> I also tried using different coap library there we did not find this issue. 
Why not just using that?

**Comment by SuneelUgar** [comment] 2022-11-04 08:07
Yes we use custom native stuff. Splitting native stuff into different jvm will not help us.
Coap californium has good support and already our code is using these api. 
We do not want to shift any other library as of now.

**Closed** 2022-11-04 08:07 UTC
Labels: could this be closed?

**Comment by boaks** [comment] 2022-11-04 08:09
Sorry, this will be just a never ending story!
If you don't split away your native stuff, I will never be able to reproduce it.

The only root-cause I see left, are resource exhausting, e.g. memory. But also that can't be fixed in Californium.
